spring.application.name=gestao-imobiliaria

# Configuração do Banco em Memória H2 (Não precisa de Docker/PostgreSQL)
spring.datasource.url=jdbc:h2:mem:fmc_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console visual do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# JPA/Hibernate (Cria as tabelas no banco em memória automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta do servidor Java
server.port=8080